# Generated by Django 3.0b1 on 2019-11-01 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MinistryName', models.CharField(max_length=100)),
                ('HonorableMinisterName', models.CharField(max_length=100)),
                ('Address', models.TextField()),
                ('Phone', models.CharField(max_length=15, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ministry',
            },
        ),
        migrations.CreateModel(
            name='GovernmentEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GovernmentEmployeeName', models.CharField(max_length=100)),
                ('GovernmentEmployeeAddress', models.TextField()),
                ('GovernmentEmployeePhnNumber', models.CharField(max_length=15)),
                ('GovernmentEmployeeGmail', models.EmailField(max_length=254)),
                ('GovernmentEmployeeDesignation', models.CharField(max_length=100)),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crud.Ministry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'govermentemployee',
            },
        ),
    ]
